public class ExceptionDemo Department of Information Technology, VJIT Page 23 Java Programming Lab Manual public static void main(String args[]) int a.b.c: Scanner in=new Scanner (System.in): /*IMPLEMENTATION OF ARITHMETIC EXCEPTION / System.out.print("\nPLEASE ENTER TWO NUMBER FOR DIVISION: "): a=in.nextInt(); b=in.nextint0: try System.out.printin("I AM IN TRY BLOCK 1"): c=a/b. System.out.printIn("\nDIVISION OF TWO NUMBER IS:"+c): catch(InputMismatchException e) System.out.printin("\nl AM IN CATCH BLOCK 1"); System.out.printin("\n CHECK INPUT \n"); System.out.printin(e); catch(ArithmeticException e) System.out.printin("\nl AM IN CATCH BLOCK 1"): System.out.printin("\nDIVISION BY ZERO IS NOT POSSIBLE
